sudo: required
services: 
  - docker

before_install:
    - docker build -t jpkeisala/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jpkeisala/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  enviroment: "Docker-env"
  bucket_name: ""
  bucket_path: 'docker-react/'
  on:
    branch:master

access_key_id:
  secure: $AWS_ACCESS_KEY
secret_access_key:
  secure: $AWS_SECRET_KEY