# Specify a base image
FROM node:alpine

WORKDIR '/app'

# Install some dependencies
COPY ./package.json ./
RUN npm install
COPY ./ ./

# Default command
CMD ["npm", "run", "start"]


# docker build -f Dockerfile.dev .
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app 8ba239412116 